export const BLOGS = [
    {
        title: "Como reduzir custos de passagens corporativas",
        desc: "Estratégias práticas para negociar acordos, usar tarifas dinâmicas e garantir compliance com políticas internas.",
        image: "/images/blog1.svg",
        category: "Gestão de Viagens",
        author: "Ana Ribeiro",
        authorRole: "Líder de Sucesso do Cliente",
        authorCompany: "Exceller Agency",
        authorCompanyUrl: "https://exceller.agency",
        authorImage: "/images/person-one.jpg",
    },
    {
        title: "Tendências de distribuição aérea para 2025",
        desc: "O que mudará com NDC, acordos direct connect e como preparar sua empresa para novos modelos de comissão.",
        image: "/images/blog2.svg",
        category: "Mercado Aéreo",
        author: "Caio Martins",
        authorRole: "Head de Produto",
        authorCompany: "Exceller Agency",
        authorCompanyUrl: "https://exceller.agency",
        authorImage: "/images/person-three.jpg",
    },
    {
        title: "Checklist para emitir bilhetes multi-trecho sem erros",
        desc: "Fluxos, documentos e conferências essenciais para garantir a melhor tarifa combinada para o seu cliente.",
        image: "/images/blog3.svg",
        category: "Operação",
        author: "Juliana Paes",
        authorRole: "Especialista em Tarifas",
        authorCompany: "Exceller Agency",
        authorCompanyUrl: "https://exceller.agency",
        authorImage: "/images/person-four.jpg",
    },
    {
        title: "Por que automatizar alertas tarifários agora",
        desc: "Conheça os ganhos de produtividade e receita ao monitorar quedas de preço e reenviar propostas automaticamente.",
        image: "/images/blog1.svg",
        category: "Tecnologia",
        author: "Victor Lima",
        authorRole: "Product Marketing",
        authorCompany: "Exceller Agency",
        authorCompanyUrl: "https://exceller.agency",
        authorImage: "/images/person-five.jpg",
    },
];
