export const TESTIMONIALS = [
    {
        name: "Marina Soares",
        role: "Gerente de Viagens",
        company: "Grupo Atlas",
        companyUrl: "https://grupoatlas.com.br",
        image: "/images/testimonials/person1.jpg",
        content: "Reduzimos 22% do gasto médio por trecho em três meses com os alertas automáticos da Exceller.",
        time: "09:12",
        date: "15 Fev 2025",
    },
    {
        name: "Felipe Andrade",
        role: "Diretor Comercial",
        company: "SkyBiz Travel",
        companyUrl: "https://skybiz.com.br",
        image: "/images/testimonials/person2.jpg",
        content: "O motor de tarifas concentra nossos GDS, NDC e consolidadores no mesmo painel. Ficou muito mais fácil negociar.",
        time: "11:48",
        date: "03 Mar 2025",
    },
    {
        name: "Larissa Monteiro",
        role: "Coordenadora de Atendimento",
        company: "Voyager Corp",
        companyUrl: "https://voyager.com",
        image: "/images/testimonials/person3.jpg",
        content: "Ganhamos agilidade com respostas em menos de dois minutos e os clientes percebem isso na hora.",
        time: "17:26",
        date: "27 Jan 2025",
    },
    {
        name: "André Carvalho",
        role: "Head de Operações",
        company: "FlyNow",
        companyUrl: "https://flynow.com",
        image: "/images/testimonials/person4.jpg",
        content: "Integramos o checkout ao nosso ERP e eliminamos retrabalho manual nos fechamentos semanais.",
        time: "08:41",
        date: "09 Dez 2024",
    },
    {
        name: "Paula Fernandes",
        role: "Especialista em Tarifas",
        company: "TravelOne",
        companyUrl: "https://travelone.com",
        image: "/images/testimonials/person1.jpg",
        content: "Os dashboards mostram a economia por cliente e ajudam a provar o valor estratégico da agência.",
        time: "15:05",
        date: "18 Nov 2024",
    },
    {
        name: "Rafael Nunes",
        role: "CEO",
        company: "Orbit Corporate",
        companyUrl: "https://orbitcorporate.com",
        image: "/images/testimonials/person2.jpg",
        content: "A Exceller trouxe previsibilidade e escala para o negócio sem perder nossa assinatura de atendimento.",
        time: "19:32",
        date: "04 Out 2024",
    },
];
